extends:
  - airbnb
  - plugin:prettier/recommended
parser: typescript-eslint-parser
plugins:
  - react
  - jsx-a11y
  - import
  - typescript
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 6
  sourceType: module

settings:
  import/resolver:
    webpack: true
    eslint-import-resolver-typescript: true
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
env:
  browser: true
rules:
  import/extensions:
    - error
    - always
    - tsx: never
      ts: never
      jsx: never
      js: never
  react/jsx-filename-extension: 0
