export interface BaseAction {
  type: string;
}

export type Action = AutoGeneratedAction;

export type AutoGeneratedAction = UpdateUserFirstName; // $$CREATE_REDUX_ACTION_SCRIPT_IDENTIFIER$$ (please do not remove this comment!)

export interface UpdateUserFirstName extends BaseAction {
  type: 'UPDATE_USER_FIRST_NAME';
  firstName: string;
}
